name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r release.zip EFI -x ".git/*" ".github/*"
    - name: Release to Github
      run: echo "Release"
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    - name: File
      run: |
        ls -la
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la