name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r /release/release.zip EFI -x ".git/*" ".github/*"
    - name: File
      run: |
        ls -la
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la